
- name: adding storage domains
  ovirt_storage_create: name={{item.name}} 
                        datacenter={{item.datacenter}}
                        host={{item.host}}
                        path={{item.path}}
                        type={{item.type}}
                        storage_type={{item.storage_type}}
                        storage_url={{item.storage_url}}
                        url={{item.engine_fqdn}}
                        username={{item.engine_user}} 
                        password={{item.engine_password}}
  with_items:
    '{{ovirt_storage_add}}'
    
    
    
  